import Head from "next/head";
import { useState, useEffect } from "react";
import { db } from "../lib/firebase";
import { addDoc, onSnapshot, query, collection } from "firebase/firestore";

export default function Home() {
	const [input, setInput] = useState("");
	const [tasks, setTasks] = useState([{ id: "", title: "" }]);

	const newTodo = async (e) => {
		await addDoc(collection(db, "tasks"), { title: input });
		setInput("");
	};

	useEffect(() => {
		const q = query(collection(db, "tasks"));
		const unSub = onSnapshot(q, (querySnapshot) => {
			setTasks(
				querySnapshot.docs.map((doc) => ({
					id: doc.id,
					title: doc.data().title,
				}))
			);
		});
		return () => unSub();
	}, []);

	return (
		<div className={`h-screen w-5/6 mx-auto flex flex-col items-center mt-16`}>
			<Head>
				<title>Next Todo App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`flex`}>
				<input
					placeholder="input new todo"
					value={input}
					onChange={(e) => setInput(e.target.value)}
					className={`border-2 border-indigo-500`}
				/>
				<button
					onClick={newTodo}
					disabled={!input}
					className={`bg-indigo-500 text-white py-1 px-2 ml-1`}>
					追加
				</button>
			</div>
			<div className={`mt-8`}>
				{tasks.map((task) => (
					<h3 key={task.id}>{task.title}</h3>
				))}
			</div>
		</div>
	);
}
